name: CI

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:

  tox:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "pypy-3.9"
          - "pypy-3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check git is working
        run: |
          git config --global user.email "bumpversion-test-git@github.actions"
          git config --global user.name "Testing Git on Travis CI"
          git --version
          git config --list
      - name: Check mercurial is working
        run: |
          echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
          hg --version
      - name: Install test dependencies
        run: pip install tox tox-gh-actions
      - name: Run setup and tests as defined in tox.ini
        run: tox
